config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  resources :shops do
    resources :reviews, only: %i[new create show edit update destroy], shallow: true
    collection do
      get "search"
      get "map"
      get "list"
      get "bookmarks"
      get "autocomplete"
    end
  end

  resource :profile, only: %i[show edit update]

  resources :shop_bookmarks, only: %i[create destroy]

  resources :diagnoses do
    collection do
      get "start", to: "diagnoses#start"
      get "question/:id", to: "diagnoses#show_question", as: "question"
      post "answer", to: "diagnoses#answer_question"
      get "result", to: "diagnoses#result"
    end
  end

  get "privacy", to: "static_pages#privacy", as: "privacy_policy"

  get "terms", to: "static_pages#terms", as: "terms"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :shop_images, dependent: :destroy
  has_many :shop_bookmarks, dependent: :destroy
  has_many :reviews, dependent: :destroy

  scope :experienced_shops, -> { where(has_experience: true) }

  def self.ransackable_attributes(auth_object = nil)
    [ "name", "address" ]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  def simplified_address
    match_data = address.match(/(.*?[都道府県].*?[市区町村].*?)(\d+[-]\d+)?/)

    if match_data
      match_data[0].strip
    else
      "住所不明"
    end
  end

  # Geocoding setup
  geocoded_by :address
  after_validation :geocode, if: ->(obj) { obj.address.present? && obj.address_changed? }

  def photo_urls
    Rails.cache.fetch([ self, "photo_urls" ], expires_in: 1.week) do
      shop_images.map do |shop_image|
        "https://maps.googleapis.com/maps/api/place/photo?maxwidth=1000&photoreference=#{shop_image.image}&key=#{GoogleApi.api_key}"
      end
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [ :bookmarks ]
  before_action :set_ransack_query, only: [ :index ]

  def index;end

  def search
    render :index
  end

  def list
    latitude = params[:latitude].to_f
    longitude = params[:longitude].to_f
    radius = 2

    nearby_shops = Shop.includes(:shop_images).near([ latitude, longitude ], radius, units: :km).limit(6)
    nearby_shops_json = generate_shops_json(nearby_shops)

    render json: nearby_shops_json
  end

  def map
    shops = Shop.includes(:shop_images)
    @shops_json = generate_shops_json(shops)
  end

  def show
    @shop = Shop.includes(:shop_images).find_by(id: params[:id])

    if @shop.nil?
      redirect_to shops_path, alert: "ショップが見つかりませんでした。"
      return
    end

    @review = Review.new
    @reviews = @shop.reviews.includes(:user).order(created_at: :desc)
    @shop_images = @shop.photo_urls
  end

  def bookmarks
    @shop_bookmarks = current_user.shop_bookmarks.includes(:shop).order(created_at: :desc)
  end

  def autocomplete
    query = params[:q]
    shops = Shop.where("name LIKE ?", "%#{query}%").select(:name).distinct.limit(5)

    render json: shops.map { |shop| { id: nil, name: shop.name } }
  end


  private

  def fetch_shops
    if params[:q].present?
      @q.result(distinct: true).includes(:shop_images)
    else
      Shop.includes(:shop_images)
    end
  end

  def fetch_filtered_shops
    shops = fetch_shops
    shops = filter_experienced_shops(shops)

    sort_param = params.dig(:q, :s)

    if sort_param.present?
      shops = apply_sorting(shops, sort_param)
    end

    paginate_shops(shops)
  end

  def filter_experienced_shops(shops) # オリジナル香水ショップのみフィルタリング
    return shops unless params.dig(:q, :has_experience_eq) == "true"

    shops.experienced_shops
  end

  def apply_sorting(shops, sort_param)
    case sort_param
    when "rating"
      shops.order(rating: :desc)
    when "reviews"
      shops
      .left_joins(:reviews)
      .select("shops.*, COUNT(reviews.id) AS reviews_count")
      .group("shops.id")
      .order("COUNT(reviews.id) DESC")
    else
      shops
    end
  end

  def paginate_shops(shops)
    shops.page(params[:page]).per(12)
  end

  def set_ransack_query
    @q = Shop.ransack(params[:q])
    @filtered_shops = fetch_filtered_shops
  end

  def generate_shops_json(shops)
    shops.map do |shop|
      first_image = shop.shop_images.first&.image
      shop.as_json(only: [ :id, :name, :latitude, :longitude, :address, :rating ]).merge(image: first_image)
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def render_rating(shop, options = {})
    full_stars = shop.rating.floor
    half_star = shop.rating - full_stars >= 0.5

    svg_class = options[:svg_size] || "w-4 h-4"
    star_svg = "<svg class='#{svg_class} text-yellow-400' fill='currentColor' viewBox='0 0 20 20'><path d='M10 15l-5.878 3.09 1.122-6.534L0 6.236l6.545-.954L10 0l2.455 5.282L20 6.236l-5.244 5.32 1.122 6.534z'></path></svg>"
    half_star_svg = "<svg class='#{svg_class} text-yellow-400' fill='currentColor' viewBox='0 0 20 20'><defs><linearGradient id='half'><stop offset='50%' stop-color='currentColor'/><stop offset='50%' stop-color='currentColor' stop-opacity='0.5'/></defs><path d='M10 15l-5.878 3.09 1.122-6.534L0 6.236l6.545-.954L10 0l2.455 5.282L20 6.236l-5.244 5.32 1.122 6.534z' fill='url(#half)'></path></svg>"
    empty_star_svg = "<svg class='#{svg_class} text-yellow-400' fill='currentColor' viewBox='0 0 20 20' opacity='0.5'><path d='M10 15l-5.878 3.09 1.122-6.534L0 6.236l6.545-.954L10 0l2.455 5.282L20 6.236l-5.244 5.32 1.122 6.534z'></path></svg>"

    rating_html = (star_svg * full_stars).html_safe
    rating_html += half_star_svg.html_safe if half_star
    rating_html += (empty_star_svg * (5 - full_stars - (half_star ? 1 : 0))).html_safe

    text_size_class = options[:text_size] || "text-base"
    rating_html + content_tag(:p, shop.rating, class: "#{text_size_class} text-yellow-400 font-semibold ml-2")
  end

  def experience_tag(shop)
    if shop.has_experience
      content_tag(:p, "#自分好みの香水を作れる", class: "w-44 text-xs rounded-full border border-gray-300 py-1 text-center")
    else
      ""
    end
  end
end

app/views/shops/_bookmark.html.erb
<%= link_to shop_bookmarks_path(shop_id: shop.id),
            id: "bookmark-button-for-shop-#{shop.id}",
            method: :post,
            data: { turbo_method: :post },
            class: "flex items-center" do %>
  <button class="flex justify-center items-center w-10 h-10 md:w-9 md:h-9 border opacity-90 rounded-full bg-gray-50 hoverable:hover:text-red-500 transition-colors text-gray-400">
    <span class="material-symbols-outlined material-icons md-30 material-symbols-outlined-bookmark" style="font-size:28px;">
      favorite
    </span>
  </button>
<% end %>

app/views/shops/_bookmark_buttons.html.erb
<% if user_signed_in? %>
  <div>
    <% if current_user.bookmark?(shop) %> <!-- 指定されたショップがブックマークされているか確認 -->
      <%= render "unbookmark", { shop: shop } %> <!-- ブックマークされている場合は「ブックマーク解除」ボタンを表示 -->
    <% else %>
      <%= render "bookmark", { shop: shop } %> <!-- ブックマークされていない場合は「ブックマーク追加」ボタンを表示 -->
    <% end %>
  </div>
<% else %>
  <!-- 未ログインユーザー処理 -->
<% end %>

app/views/shops/_search_form.html.erb
<%= search_form_for @q, url: shops_path, method: :get, data: { turbo_frame: "search_results" }, html: { class: "bg-gray-50 rounded-md border border-gray-300 shadow-sm flex items-center p-1 w-full shadow-sm" } do |f| %>

  <div data-controller="autocomplete" data-autocomplete-url-value="<%= autocomplete_shops_path %>" class="relative w-full" role="combobox">
    <div class="flex items-center w-full">
      <span class="material-symbols-outlined text-gray-400 mx-1" style="font-variation-settings: 'FILL' 1;">search</span>
      <%= f.search_field :name_or_address_cont, placeholder: "ショップ名や住所から探す", class: "w-full outline-none bg-gray-50 autofill:bg-transparent text-sm autofill:shadow-[inset_0_0_0px_1000px_theme(colors.gray.50)]", data: { "autocomplete-target": "input" } %>
      <%= f.submit "検索", class: "bg-main text-white text-center text-sm rounded-md p-2 w-20 my-btn cursor-pointer" %>
    </div>

    <%= f.hidden_field :name, data: { "autocomplete_target": "hidden" } %>

    <ul data-autocomplete-target="results" class="absolute left-0 right-0 bg-white rounded-md shadow-lg mt-2 max-h-60 overflow-auto z-50"></ul>
  </div>
<% end %>

app/views/shops/_search_results.html.erb
<% if @q.name_or_address_cont.present? %>
  <p class="text-gray-700 mt-5">「<%= @q.name_or_address_cont %>」の検索結果：<span class="font-medium"><%= @filtered_shops.length %>件</span></p>
<% end %>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 mt-5 border-t divide-gray-200 pt-10">
    <% @filtered_shops.each do |shop| %>
      <div class="bg-white shadow-sm border group rounded-md hover:opacity-90 duration-300">
        <a href="/shops/<%= shop.id %>" data-turbo="false">
          <div class="relative w-full h-36 flex items-center justify-center overflow-hidden">
            <% if shop.photo_urls.any? %>
              <%= image_tag shop.photo_urls.first, alt: "#{shop.name}の画像", class: "object-cover w-full h-full transition-transform duration-300 hoverable:group-hover:scale-105 ghoverable:roup-hover:opacity-85", loading: "lazy" %>
            <% end %>
            <!-- bookmark_buttonsを配置 -->
            <object class="absolute top-4 right-4">
              <%= render 'bookmark_buttons', { shop: shop } %>
            </object>
          </div>
          <div class="p-4 pb-8 flex flex-col flex-grow">
            <div class="flex justify-between items-center">
              <p class="text-xs text-secondary dark:text-neutral-500 mr-2"><%= shop.simplified_address %></p>
            </div>
            <h3 class="text-base font-semibold mb-1 line-clamp-2"><%= shop.name %></h3>
            <div class="flex items-center mb-2">
              <%= render_rating(shop) %>
            </div>
            <%= experience_tag(shop) %>
          </div>
        </a>
      </div>
    <% end %>
  </div>
  <%= paginate @filtered_shops %>

  <% if @filtered_shops.blank? %>
    <p class="text-center mt-8 text-sm sm:text-base">指定された条件ではショップが見つかりませんでした。<br>
      検索キーワードを変更して、再度検索してください。</p>
  <% end %>

app/views/shops/_shop_bookmark.html.erb
  <div class="bg-white border shadow-sm hover:opacity-90 duration-300 group rounded-md">
    <a href="/shops/<%= bookmark.shop.id %>" data-turbo="false">
      <div class="relative w-full h-36 flex items-center justify-center overflow-hidden">
        <% if bookmark.shop.photo_urls.any? %>
          <%= image_tag bookmark.shop.photo_urls.first,
              alt: "#{bookmark.shop.name}の画像",
              class: "object-cover w-full h-full transition-transform duration-300 hoverable:group-hover:scale-105 ghoverable:roup-hover:opacity-85",
              loading: "lazy" %>
        <% end %>
        <!-- bookmark_buttonsを配置 -->
        <object class="absolute top-4 right-4">
          <%= render 'bookmark_buttons', { shop: bookmark.shop } %>
        </object>
      </div>
      <div class="p-4 pb-8 flex flex-col flex-grow">
        <div class="flex justify-between items-center">
          <p class="text-xs text-secondary dark:text-neutral-500 mr-2">
            <%= bookmark.shop.simplified_address %>
          </p>
        </div>
        <h3 class="text-base font-semibold mb-1 line-clamp-2">
          <%= bookmark.shop.name %>
        </h3>
        <div class="flex items-center mb-2">
          <%= render_rating(bookmark.shop) %>
        </div>
        <%= experience_tag(bookmark.shop) %>
      </div>
    </a>
  </div>

app/views/shops/_sidebar.html.erb
<aside id="default-sidebar" data-sidebar-target="sidebar" class="lg:mt-16 fixed top-0 left-0 w-full lg:w-64 lg:min-w-64 h-screen transition-transform -translate-x-full lg:translate-x-0 z-10 lg:z-0 lg:hidden duration-400" aria-label="Sidebar">
  <div class="h-full px-3 py-4 overflow-y-auto bg-white lg:border-r-4 lg:border-primary lg:border-double pb-20">

    <div class="shop-list w-full px-4 mx-auto"></div>

    <button data-action="click->sidebar#toggleButton" aria-controls="default-sidebar" type="button" class="lg:hidden z-50 text-white rounded-lg h-20 w-24 bg-main opacity-90 flex flex-col items-center justify-center font-bold right-4 bottom-20 absolute shadow">
      <span class="material-symbols-outlined mb-1 text-white" style="font-size: 30px;">arrow_back</span>
      <span style="font-size: 13px;">マップに戻る</span>
    </button>
  </div>
</aside>

app/views/shops/_sort_form.html.erb
<div class="mt-8 flex md:justify-end justify-items-end ml-auto">
  <%= search_form_for @q, html: { id: 'filter-form', method: :get }, class: "ml-auto md:flex justify-items-end md:items-center" do |f| %>
    <%= hidden_field_tag 'q[name_or_address_cont]', params.dig(:q, :name_or_address_cont) %>

    <div class="form-control md:mr-4">
      <label class="label cursor-pointer">
        <span class="label-text mr-2">香水が作れるショップのみ表示</span>
        <input type="checkbox" name="q[has_experience_eq]" value="true" class="toggle toggle-primary"
              <%= params.dig(:q, :has_experience_eq) == 'true' ? 'checked' : '' %>
              onchange="this.form.submit();" />
      </label>
    </div>

    <div class="flex justify-end mt-3 md:mt-0">
      <select name="q[s]" class="select select-bordered min-h-2 h-8 rounded border-gray-400 justify-items-end" onchange="this.form.submit()">
        <option value="" <%= "selected" if params.dig(:q, :s).blank? %>>並び替え（標準）</option>
        <option value="rating" <%= "selected" if params.dig(:q, :s) == "rating" %>>評価が高い順</option>
        <option value="reviews" <%= "selected" if params.dig(:q, :s) == "reviews" %>>口コミが多い順</option>
      </select>
    </div>
  <% end %>
</div>

app/views/shops/_unbookmark.html.erb
<%= link_to shop_bookmark_path(current_user.shop_bookmarks.find_by(shop_id: shop.id)),
            id: "unbookmark-button-for-shop-#{shop.id}",
            method: :delete,
            data: { turbo_method: :delete },
            class: "flex items-center" do %>
  <button class="flex justify-center items-center w-10 h-10 md:w-9 md:h-9 border opacity-90 rounded-full bg-gray-50 text-red-500">
    <span class="material-symbols-outlined material-symbols-outlined-unbookmark material-icons md-30" style="font-size:28px;">
      favorite
    </span>
  </button>
<% end %>

app/views/shops/bookmarks.html.erb
<% content_for(:title, t('.title')) %>
<div class="w-11/12 md:max-w-screen-xl mx-auto mb-20 p-4 py-9 md:px-8 mt-12 rounded-md bg-baseColor shadow-custom">
  <h2 class="text-xl md:text-2xl font-bold">お気に入りショップ一覧</h2>

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 mt-6">
    <% if @shop_bookmarks.any? %>
      <% @shop_bookmarks.each do |bookmark| %>
        <%= render partial: "shop_bookmark", locals: { bookmark: bookmark } %>
      <% end %>
    <% end %>
  </div>

  <% if @shop_bookmarks.blank? %>
    <div class="mt-8 text-center">
      <h3 class="text-lg font-semibold">まだお気に入りがありません</h3>
      <p class="text-sm md:text-base">気になるショップを見つけたら、<span class="block sm:inline">ぜひ追加してみましょう！</p>
      <div class="mt-6">
        <%= link_to "ショップを探す", shops_path, class: "bg-main btn-wide py-3 px-12 text-white rounded hover:bg-opacity-90 transition duration-200" %>
      </div>
    </div>
  <% end %>
</div>

app/views/shops/index.html.erb
<%= content_for(:title, t(".title")) %>
<div class="w-11/12 md:max-w-screen-xl mx-auto mb-20 p-4 py-10 md:py-11 md:px-8 mt-12 rounded-md bg-baseColor shadow-custom">
  <div class="">
    <div class="w-full md:max-w-screen-sm mx-auto">
      <%= render "search_form", q: @q, url: shops_path %>
    </div>
    <%= turbo_frame_tag "search_results", data: { turbo_action: :advance }  do %>
      <%= render 'sort_form' %>
      <%= render partial: 'search_results', locals: { filtered_shops: @filtered_shops } %>
    <% end %>
  </div>
</div>

app/views/shops/map.html.erb
<% content_for(:title, t('shops.map.title')) %>
<div class="mx-auto md:mb-20">
  <div id="map-container">
    <div id="map" class="w-full relative rounded h-screen lg:h-[600px] md:mb-8"></div>

    <div class="absolute right-4 bottom-20 md:bottom-60 z-50">
      <!-- SPのみ ドロワー表示 -->
      <div data-controller="sidebar">
        <%= render "shops/sidebar" %>
        <button data-action="click->sidebar#toggleButton" aria-controls="default-sidebar" type="button" class="lg:hidden z-50 text-white rounded-lg h-20 w-24 md:w-20 bg-main opacity-90 flex flex-col items-center justify-center font-bold mb-3 py-2 hover:brightness-105 transition duration-200" data-sidebar-target="toggleButton">
          <span class="material-symbols-outlined text-white" style="font-size: 35px;">store</span>
          <span data-sidebar-target="buttonText" style="font-size: 13px;">周辺ショップ</span>
        </button>
      </div>
      <!-- // SPのみ ドロワー表示 -->

      <button id="show-location-btn" class="text-white rounded-lg h-18 w-18 bg-main opacity-90 flex flex-col items-center justify-center font-bold w-24 h-20 md:w-20 shadow hover:brightness-105 transition duration-200" style="font-size: 13px;">
        <span class="material-symbols-outlined mb-1 text-white" style="font-size: 35px;">my_location</span>
        現在地を表示
      </button>

      <%= link_to shops_path, class: "hidden md:flex text-main rounded-lg h-18 w-18 opacity-90 bg-white flex flex-col items-center justify-center font-bold w-20 h-20 shadow hover:brightness-105 transition duration-200 mt-3 border border-main", style: 'font-size: 13px;' do %>
        <span class="material-symbols-outlined mb-1 text-main" style="font-size: 30px;">arrow_back</span>
        <p>一覧に戻る</p>
      <% end %>
    </div>

    <div class="shop-list bg-baseColor rounded-md p-4 w-full md:max-w-screen-xl mx-auto hidden lg:block shadow-custom">
      <!-- 現在地周辺の店舗を表示 -->
    </div>
  </div>

  <div id="loading" class="fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 hidden">
    <%= image_tag("loading.gif", class: "w-36 h-36", alt: "Loading...") %>
  </div>
</div>

<script type="text/javascript">
  const googleMapApiKey = "<%= ENV['GOOGLE_API_KEY'] %>";
  const shops = <%= sanitize @shops_json.to_json %>;
  const initialZoomLevel = 16;

  const MapApp = {
    map: null,
    currentLocationCircle: null,
    currentInfoWindow: null,
  };

  function initMap() {
    showLoading();
    initializeMap();
    initializeEventListeners();
    showCurrentLocation().finally(() => {
      hideLoading();
    });
    displayShopMarkers();
  }

  function showLoading() {
    const loadingDiv = document.getElementById("loading");
    loadingDiv.classList.remove("hidden");
  }

  function hideLoading() {
    const loadingDiv = document.getElementById("loading");
    loadingDiv.classList.add("hidden");
  }

  function initializeMap() {
    const mapDiv = document.getElementById("map");
    MapApp.map = new google.maps.Map(mapDiv, {
      disableDefaultUI: true, // デフォルトのUIを非表示
      gestureHandling: "greedy", // ドラッグ操作を可能
      zoom: initialZoomLevel,
    });
  }

  function initializeEventListeners() {
    const showLocationButton = document.getElementById("show-location-btn");
    showLocationButton.addEventListener("click", showCurrentLocation);
  }

  // 現在地を取得してマップを更新
  async function showCurrentLocation() {
    try {
      if (!navigator.geolocation) {
        alert('お使いのブラウザでは位置情報の取得がサポートされていません。');
        MapApp.map.setCenter({ lat: 35.6803997, lng: 139.7690174 }); // 東京駅の座標
        return;
      }

      const position = await getUserLocation();
      const userLocation = {
        lat: position.coords.latitude,
        lng: position.coords.longitude,
      };

      updateMapCenter(userLocation);
      displayCurrentLocationMarker(userLocation);

      await fetchNearbyShops(userLocation.lat, userLocation.lng);
    } catch (error) {
      alert('位置情報の取得に失敗しました。');
      MapApp.map.setCenter({ lat: 35.6803997, lng: 139.7690174 });
    }
  }

  function getUserLocation() {
    return new Promise((resolve, reject) => {
      if (!navigator.geolocation) {
        return reject(new Error("現在地を取得出来ませんでした"));
      }
      navigator.geolocation.getCurrentPosition(resolve, reject);
    });
  }

  // マップ位置を中心に指定
  function updateMapCenter(location) {
    MapApp.map.setCenter(location);
    MapApp.map.setZoom(initialZoomLevel);
  }

  // 現在地のマーカーを作成
  function displayCurrentLocationMarker(location) {
    if (MapApp.currentLocationCircle) {
      MapApp.currentLocationCircle.setMap(null);
    }

    MapApp.currentLocationCircle = new google.maps.Circle({
      strokeColor: '#e57777',
      strokeOpacity: 0.2,
      strokeWeight: 1,
      fillColor: '#e57777',
      fillOpacity: 0.2,
      map: MapApp.map,
      center: location,
      radius: 40,
    });

    new google.maps.Marker({
      position: location,
      map: MapApp.map,
      icon: {
        path: google.maps.SymbolPath.CIRCLE,
        fillColor: '#e57777',
        fillOpacity: 1,
        strokeColor: 'white',
        strokeWeight: 2,
        scale: 7,
      },
    });
  }

  // 周辺のショップ情報を取得
  async function fetchNearbyShops(lat, lng) {
    try {
      const response = await fetch(`/shops/list?latitude=${lat}&longitude=${lng}`);
      const shops = await response.json();
      displayShopList(shops);
    } catch (error) {
      console.error('周辺店舗の取得に失敗しました:', error);
    }
  }

  // 現在地周辺のショップを表示
  function displayShopList(shops) {
    const shopListElements = document.querySelectorAll('.shop-list');

    shopListElements.forEach(shopListElement => {
      shopListElement.innerHTML = '<h2 class="text-lg md:text-2xl text-center font-bold mt-2 mb-5">現在地から近いショップ</h2>';

      if (shops.length > 0) {
        const ul = document.createElement('ul');
        ul.className = "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8";

        shops.forEach(shop => {
          const li = createShopListItem(shop);
          ul.appendChild(li);
        });
        shopListElement.appendChild(ul);
      } else {
        shopListElement.innerHTML += '<p class="text-base text-center mb-4">周辺にショップが見つかりませんでした。</p>';
      }
    });
  }

  function createShopListItem(shop) {
    const li = document.createElement('li');
    li.className = "border rounded shadow-sm flex flex-col hover:opacity-90 duration-300 group";

    const imageUrl = `https://maps.googleapis.com/maps/api/place/photo?maxheight=300&maxwidth=300&photo_reference=${shop.image}&key=${googleMapApiKey}`;
    const shopLink = `/shops/${shop.id}`;
    li.innerHTML = `
      <a href="${shopLink}" class="flex flex-col h-full">
        <div class="w-full h-36 overflow-hidden mb-0">
          <img src="${imageUrl}" alt="${shop.name}" class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105 group-hover:opacity-85" loading="lazy">
        </div>
        <div class="flex flex-col flex-grow p-4 pb-8">
          <h3 class="text-base font-semibold mb-1 line-clamp-2">${shop.name}</h3>
          <div class="flex items-center mb-2">
            ${generateStarRating(shop.rating)}
            <p class="text-base text-yellow-400 font-semibold ml-2">${shop.rating}</p>
          </div>
        </div>
      </a>
    `;

    return li;
  }

  function generateStarRating(rating) {
    const fullStars = Math.floor(rating);
    const halfStar = rating - fullStars >= 0.5;
    const emptyStars = 5 - fullStars - (halfStar ? 1 : 0);

    const starSVG = (type, opacity = 1) => `
      <svg class="w-4 h-4 text-yellow-400" fill="currentColor" style="opacity: ${opacity}" viewBox="0 0 20 20">
        <path d="M10 15l-5.878 3.09 1.122-6.534L0 6.236l6.545-.954L10 0l2.455 5.282L20 6.236l-5.244 5.32 1.122 6.534z" />
      </svg>
    `;

    return `
      ${starSVG('full').repeat(fullStars)}
      ${halfStar ? starSVG('half') : ''}
      ${starSVG('empty', 0.5).repeat(emptyStars)}
    `;
  }

  // マップ上にショップのマーカーを表示
  function displayShopMarkers() {
    shops.forEach(shop => createMarker(shop));
  }

  function createMarker(shop) {
    const marker = new google.maps.Marker({
      map: MapApp.map,
      position: {
        lat: parseFloat(shop.latitude),
        lng: parseFloat(shop.longitude),
      },
      title: shop.name,
    });
    marker.addListener("click", () => handleMarkerClick(marker, shop));
  }

  // マーカークリック時の処理
  function handleMarkerClick(marker, shop) {
    if (MapApp.currentInfoWindow) {
      MapApp.currentInfoWindow.close();
    }

    const imageUrl = `https://maps.googleapis.com/maps/api/place/photo?maxheight=300&maxwidth=300&photo_reference=${shop.image}&key=${googleMapApiKey}`;
    const infoWindowContent = generateInfoWindowContent(shop, imageUrl);

    MapApp.currentInfoWindow = new google.maps.InfoWindow({
      content: infoWindowContent,
    });

    MapApp.currentInfoWindow.open(MapApp.map, marker);
  }

  function generateInfoWindowContent(shop, imageUrl) {
    return `
      <div class="w-52 p-3 pt-0 rounded shadow flex flex-col items-center">
        <h3 class="text-base font-semibold mb-2 text-center line-clamp-2">${shop.name}</h3>
        <div class="flex items-center mb-2">
          ${generateStarRating(shop.rating)}
          <p class="text-base text-yellow-400 font-semibold ml-2">${shop.rating}</p>
        </div>
        <img src="${imageUrl}" alt="${shop.name}" class="w-full h-32 object-cover mb-4" loading="lazy">
        <a href="/shops/${shop.id}" class="w-full text-sm text-center border-custom border-2 rounded py-2 transition-all hover:border-main hover:text-main">詳細を見る</a>
      </div>
    `;
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_API_KEY"] %>&callback=initMap" defer></script>