config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  resources :shops do
    resources :reviews, only: %i[new create show edit update destroy], shallow: true
    collection do
      get "search"
      get "map"
      get "list"
      get "bookmarks"
      get "autocomplete"
    end
  end

  resource :profile, only: %i[show edit update]

  resources :shop_bookmarks, only: %i[create destroy]

  resources :diagnoses do
    collection do
      get "start", to: "diagnoses#start"
      get "question/:id", to: "diagnoses#show_question", as: "question"
      post "answer", to: "diagnoses#answer_question"
      get "result", to: "diagnoses#result"
    end
  end

  get "privacy", to: "static_pages#privacy", as: "privacy_policy"

  get "terms", to: "static_pages#terms", as: "terms"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController
  before_action :initialize_user_answers, only: [ :answer_question ]
  before_action :set_question, only: [ :show_question ]

  DIAGNOSIS_DATA_KEY = :diagnosis_data

  def start;end

  def show_question
    @total_questions = Question.count
    @current_question_id = params[:id].to_i
    @previous_question_id = @current_question_id - 1
  end

  def answer_question
    session[:user_answers][params[:question_id]] = params[:answer]
    redirect_to next_question_or_results(params[:question_id])
  end

  def result
    initialize_user_fragrance_form
    @scores = @user_fragrance_form.calculate_scores
    @recommended_fragrance = find_recommended_fragrance(@scores)

    if @recommended_fragrance
      save_diagnosis_or_session
    else
      flash.now[:danger] = "診断結果を保存出来ませんでした。"
      ender :new, status: :unprocessable_entity
    end
  end

  private

  def initialize_user_fragrance_form
    @user_fragrance_form = UserFragranceForm.new(user_answers: session[:user_answers])
  end

  def initialize_user_answers
    session[:user_answers] ||= {}
  end

  def set_question
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  def next_question_or_results(current_question_id)
    next_question_id = current_question_id.to_i + 1
    Question.exists?(next_question_id) ? question_diagnoses_path(next_question_id) : result_diagnoses_path
  end

  def find_recommended_fragrance(scores)
    top_fragrance_name = scores.key(scores.values.max)
    recommended_fragrance = Fragrance.find_by(image_url: "#{top_fragrance_name}.jpg")

    recommended_fragrance
  end

  def save_diagnosis_or_session
    if current_user
      Diagnosis.create_with_scores(current_user, @recommended_fragrance.id, @scores)
    else
      session[DIAGNOSIS_DATA_KEY] = {
        fragrance_id: @recommended_fragrance.id,
        score: @scores
      }
    end
  end
end

app/views/diagnoses/result.html.erb
<% content_for(:title, t('diagnoses.start.result')) %>
<div class="min-h-screen pt-20" style="background-image: radial-gradient(farthest-corner at 90% 50px, #FFEEEF 0%, #FFF8F6 30%, #FFEDEF 55%, #FCE7E3 100%);">
  <div class="w-11/12 md:max-w-screen-xl mx-auto rounded-md bg-baseColor shadow-custom p-4 pb-8 md:pb-9 mb-20 pt-10">
    <h2 class="text-2xl md:text-3xl font-semibold text-center text-main">診断結果</h2>
    <p class="text-center mt-4 text-lg md:text-lg font-semibold">あなたには「<%= @recommended_fragrance.name %>」系<br class="md:hidden">の香りがおすすめです！</p>

  <div class="mt-4 flex flex-col md:flex-row justify-center items-start space-y-6 md:space-y-0 md:space-x-6 items-center">
    <!-- 香りの画像 -->
    <div class="md:w-96 flex flex-col items-center">
      <h3 class="text-lg font-medium text-center mt-6 mb-2 text-gray-700">おすすめの香りについて</h3>
      <%= image_tag(@recommended_fragrance.image_url, alt: "#{@recommended_fragrance.name}の画像", class: "w-full h-full rounded-lg shadow-lg") %>
    </div>

    <!-- Chart.js -->
    <div class="md:w-96 flex flex-col items-center">
      <h3 class="text-lg font-medium text-center mt-6 mb-2 text-gray-700">香りのタイプ別評価</h3>
      <div class="w-full shadow-lg bg-white rounded-lg overflow-hidden flex items-center justify-center p-4">
        <canvas id="myChart" class="h-full w-full"></canvas>
      </div>
    </div>
  </div>

    <% unless user_signed_in? %>
      <div class="text-center mt-10">
        <p class="text-base mb-7">
          アカウント登録またはログインすることで、<br>
          <span class="text-main">今回の診断結果をマイページから、<br class="md:hidden">
          いつでも見返すことができます！</span>
        </p>
        <%= link_to 'アカウント登録・ログインはこちら', user_session_path, class: "text-sm font-medium bg-main text-white rounded-lg px-4 py-4 shadow hover:opacity-90 transition duration-200" %>
      </div>
    <% end %>

    <div class="mt-10 flex flex-col items-center">
      <h3 class="text-base mb-3 text-gray-700 font-medium">診断結果をXにシェアする</h3>
      <% share_url = "https://twitter.com/share?url=https://www.fragrance-me.com/" %>
      <% share_text = "あなたにおすすめの香りは「#{@recommended_fragrance.name}」系です！\n\nFragranceMeでお気に入りの香りを見つけましょう！\n" %>

      <%= link_to "#{share_url}&text=#{ERB::Util.url_encode(share_text)}", target: '_blank', class: "flex items-center justify-center w-32 h-12 bg-subColor text-black rounded-lg shadow transition-transform transform hover:scale-105 hover:opacity-90" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512" class="w-5 h-5 mr-2 text-black opacity-80">
          <path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"></path>
        </svg>
        シェア
      <% end %>
    </div>

    <div class="mt-10 text-center">
      <%= link_to 'もう一度診断する', start_diagnoses_path, class: "text-base link transition duration-200 hover:text-main" %>
    </div>
  </div>
</div>

<script>

document.addEventListener('turbo:load', function() {

  const ctx = document.getElementById('myChart');

  // スマートフォン用のフォントサイズを設定
  const isMobile = window.matchMedia('(max-width: 640px)').matches; // 640px以下の場合

  const myChart = new Chart(ctx, {
    type: 'radar',
    data: {
      labels: ['フローラル', '柑橘', 'スパイシー', 'オリエンタル', 'ハーブ', 'ウッディ'],
      datasets: [{
        data: [<%= @scores[:floral] %>, <%= @scores[:citrus] %>, <%= @scores[:spicy] %>, <%= @scores[:oriental] %>, <%= @scores[:herbal] %>, <%= @scores[:woody] %>],
        backgroundColor: [
          'rgba(255, 99, 132, 0.2)',
        ],
        borderColor: [
          'rgba(255, 99, 132, 1)',
        ],
        borderWidth: 1
      }]
    },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      scales: {
        r: {
          min: 0,
          max: 10,
          ticks: {
            stepSize: 2, // ステップサイズ
            font: {
              size: isMobile ? 12 : 14 // スマホの場合は10px、それ以外は14px
            }
          },
          pointLabels: {
            font: {
              size: isMobile ? 12 : 15 // スマホの場合は12px、それ以外は15px
            }
          }
        }
      },
      plugins: {
        legend: {
          display: false // 凡例を非表示
        }
      }
    }
  });
  });
</script>

app/views/diagnoses/show_question.html.erb
<div class="min-h-screen pt-20" style="background-image: radial-gradient(farthest-corner at 90% 50px, #FFEEEF 0%, #FFF8F6 30%, #FFEDEF 55%, #FCE7E3 100%);">
  <div class="w-11/12 md:max-w-screen-xl mx-auto px-3 py-12 rounded-md bg-baseColor shadow-custom">

    <div class="text-center">
      <p class="-mb-1"><%= "#{@current_question_id}/#{@total_questions}" %></p>
      <progress class="progress progress-primary bg-gray-200 w-64 h-3" value="<%= @current_question_id %>" max="<%= @total_questions %>"></progress>
    </div>

    <h2 class="text-base md:text-xl font-bold mb-8 mt-6 text-center">Q. <%= @question.content %></h2>

    <%= form_with url: answer_diagnoses_path, method: :post, local: true do |f| %>
      <div class="space-y-6 w-full md:max-w-[50%] mx-auto">
        <% @answers.each do |answer| %>
          <div class="flex justify-center items-center p-4 rounded-md border border-gray-300 hover:bg-main  hover:text-white duration-200 cursor-pointer" onclick="document.getElementById('answer_<%= answer.id %>').checked = true; this.closest('form').submit();">
            <%= f.radio_button :answer, answer.id, id: "answer_#{answer.id}", class: "hidden" %>
            <span class="text-sm md:text-base"><%= answer.content %></span>
          </div>
        <% end %>
      </div>
      <%= hidden_field_tag :question_id, @question.id %>
    <% end %>
      <% if @previous_question_id >= 1 %>
        <div class="mt-10 md:ml-12 text-sm flex items-center hover:text-main transition">
          <span class="material-symbols-outlined" style="font-size: 25px;">arrow_back</span>
          <%= link_to "前の質問に戻る", question_diagnoses_path(@previous_question_id) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/diagnoses/start.html.erb
<% content_for(:title, t('.title')) %>
<div class="min-h-screen pt-20" style="background-image: radial-gradient(farthest-corner at 90% 50px, #FFEEEF 0%, #FFF8F6 30%, #FFEDEF 55%, #FCE7E3 100%);">
  <div class="w-11/12 md:max-w-screen-xl mx-auto py-20 px-2 rounded-md bg-baseColor shadow-custom">
    <div class="text-center mb-6 ">
      <h2 class="text-xl md:text-3xl font-bold text-gray-800">香りタイプ診断</h2>
      <p class="mt-3 text-center text-sm md:text-base text-gray-600">香りは心を豊かにし、周囲に素敵な印象を<br class="block md:hidden">もたらします。<br>
      この診断を通じて、<br class="block md:hidden">あなたにぴったりの香りを見つけてみましょう！
      </p>
    </div>

    <div class="flex justify-center">
      <%= link_to '診断を始める', question_diagnoses_path(1), class: "bg-main text-white rounded-lg px-12 py-3 shadow transition duration-300 hover:opacity-90" %>
    </div>
  </div>
</div>