config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  resources :shops do
    resources :reviews, only: %i[new create show edit update destroy], shallow: true
    collection do
      get "search"
      get "map"
      get "list"
      get "bookmarks"
      get "autocomplete"
    end
  end

  resource :profile, only: %i[show edit update]

  resources :shop_bookmarks, only: %i[create destroy]

  resources :diagnoses do
    collection do
      get "start", to: "diagnoses#start"
      get "question/:id", to: "diagnoses#show_question", as: "question"
      post "answer", to: "diagnoses#answer_question"
      get "result", to: "diagnoses#result"
    end
  end

  get "privacy", to: "static_pages#privacy", as: "privacy_policy"

  get "terms", to: "static_pages#terms", as: "terms"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.html.erb
<header class="navbar bg-base-100 w-full h-16 z-50 border-t-4 border-main bg-baseColor shadow-custom">
  <div class="flex justify-between items-center w-full">
    <div class="flex items-center flex-1">
      <h1>
        <a href="/" class="btn btn-ghost text-xl">FragranceMe</a>
      </h1>
      <p class="text-xs font-medium hidden lg:block">あなたにぴったりの香りに出会える、フレグランスショップ検索サイト</p> <!-- ml-2を追加 -->
    </div>

    <div class="flex-none items-center">
      <%= link_to new_user_session_path, class: "flex items-center rounded mx-1 px-3 py-2 bg-main text-sm text-white hover:opacity-90 duration-300" do %>
        <span class="material-symbols-outlined pr-1">login</span>
        ログイン
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="bg-red-100 text-sm text-red-700 px-3 py-3 mb-5 rounded-xl relative flex items-center">
    <span class="material-symbols-outlined mr-2">
      error
    </span>
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="bg-baseColor text-gray-600 py-4 shadow-custom">
  <div class="container mx-auto">
    <div class="flex flex-col sm:flex-row justify-between items-center px-2">
      <div class="w-full sm:w-1/2 text-center sm:text-left text-sm">
        <p>© 2024. FragranceMe</p>
      </div>
      <div class="flex flex-col sm:flex-row w-full mt-1 md:mt-0 sm:w-auto text-sm text-center sm:text-right space-y-1 sm:space-y-0 sm:space-x-4"> <!-- flex-colを追加 -->
        <div>
          <%= link_to "プライバシーポリシー", privacy_policy_path %>
        </div>
        <div>
          <%= link_to "利用規約", terms_path %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="navbar bg-base-100 w-full h-16 z-50 border-t-4 border-main bg-baseColor shadow-custom">
  <div class="flex justify-between items-center w-full">
    <div class="flex items-center flex-1">
      <h1>
        <a href="/" class="btn btn-ghost text-xl">FragranceMe</a>
      </h1>
      <p class="text-xs font-medium hidden lg:block">あなたにぴったりの香りに出会える、フレグランスショップ検索サイト</p>
    </div>

    <div class="flex-none">
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <%= image_tag "default_avatar.png", alt: "アバター画像" %>
          </div>
        </div>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content bg-white rounded-lg shadow-lg mt-3 w-52 transition-all duration-300 ease-in-out">
          <li class="flex hover:bg-gray-100 rounded-md transition duration-200 p-2">
            <%= link_to profile_path, class: "flex items-center w-full text-gray-800 transition duration-200", data: { turbo: false } do %>
              <span class="material-symbols-outlined text-gray-600 mr-1 transition duration-200">person</span>
              マイページ
            <% end %>
          </li>

          <li class="flex hover:bg-gray-100 rounded-md transition duration-200 p-2 hover:text-main">
            <%= link_to destroy_user_session_path, class: "flex items-center w-full text-gray-800 transition duration-200", data: { turbo_method: :delete } do %>
              <span class="material-symbols-outlined text-gray-600 mr-1 transition duration-200">logout</span>
              ログアウト
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_navigation.html.erb
<!-- PCメニュー -->
<aside id="default-sidebar" class="shadow-custom fixed top-0 left-0 h-full z-10 w-16 transition-all duration-200 ease-in-out hidden lg:block bg-baseColor">
  <div class="h-full pt-20 w-full overflow-hidden ">
    <ul class="h-full">
      <li class="group h-16 menu-item flex items-center">
        <%= link_to shops_path, class: "flex items-center p-4 transition", style: ("font-variation-settings: 'FILL' 1" if current_page?('/shops') || (request.path.start_with?('/shops/') && params[:id])) do %>
          <span class="material-symbols-outlined" style="font-size:29px; <%= 'font-variation-settings: \'FILL\' 1, \'wght\' 500; color: #e57777;' if current_page?('/shops') || (request.path.start_with?('/shops/') && params[:id]) %>">search</span>
          <span class="flex-1 ml-3 text-sm text-transition" style="<%= 'color: #e57777;' if current_page?('/shops') || (request.path.start_with?('/shops/') && params[:id]) %>">一覧から探す</span>
        <% end %>
      </li>

      <li class="group h-16 menu-item flex items-center">
        <%= link_to map_shops_path, class: "flex items-center p-4 transition", style: ("font-variation-settings: 'FILL' 1;" if current_page?('/map_shops')) do %>
          <span class="material-symbols-outlined" style="font-size:29px; <%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/shops/map') %>">map_search</span>
          <span class="flex-1 ml-3 text-sm text-transition" style="<%= 'color: #e57777;' if current_page?('/shops/map') %>">現在地から探す</span>
        <% end %>
      </li>

      <li class="group h-16 menu-item flex items-center">
        <%= link_to bookmarks_shops_path, class: "flex items-center p-4 transition", style: ("font-variation-settings: 'FILL' 1;" if current_page?('/bookmarks_shops')) do %>
          <span class="material-symbols-outlined" style="font-size:29px; <%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/shops/bookmarks') %>">favorite</span>
          <span class="flex-1 ml-3 text-sm text-transition" style="<%= 'color: #e57777;' if current_page?('/shops/bookmarks') %>">お気に入り</span>
        <% end %>
      </li>

      <li class="group h-16 menu-item flex items-center">
        <%= link_to start_diagnoses_path, class: "flex items-center p-4 transition", style: ("font-variation-settings: 'FILL' 1;" if current_page?('/start_diagnoses')) do %>
          <span class="material-symbols-outlined" style="font-size:31px; <%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/diagnoses/start') %>">edit_note</span>
          <span class="flex-1 ml-3 text-sm text-transition" style="<%= 'color: #e57777;' if current_page?('/diagnoses/start') %>">香りタイプ診断</span>
        <% end %>
      </li>

      <li class="group h-16 menu-item flex items-center">
        <%= link_to profile_path, class: "flex items-center p-4 transition" do %>
          <span class="material-symbols-outlined" style="font-size:30px; <%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/profile') %>">person</span>
          <span class="flex-1 ml-3 text-sm text-transition" style="<%= 'color: #e57777;' if current_page?('/profile') %>">マイページ</span>
        <% end %>
      </li>
    </ul>
  </div>
</aside>

<!-- SPメニュー -->
<div class="fixed bottom-0 left-0 z-50 w-full h-16 bg-gray-50 shadow border-t border-gray-200 block lg:hidden">
  <div class="grid h-full max-w-lg grid-cols-5 mx-auto font-medium">
    <%= link_to shops_path, class: "inline-flex flex-col items-center justify-center px-1" do %>
      <span class="material-symbols-outlined text-2xl" style="<%= 'font-variation-settings: \'FILL\' 1, \'wght\' 300; color: #e57777;' if current_page?('/shops') || (request.path.start_with?('/shops/') && params[:id]) %>">search</span>
      <span class="text-[9px]" style="<%= 'color: #e57777;' if current_page?('/shops') || (request.path.start_with?('/shops/') && params[:id]) %>">一覧から探す</span>
    <% end %>

    <%= link_to map_shops_path, class: "inline-flex flex-col items-center justify-center px-1" do %>
      <span class="material-symbols-outlined text-2xl" style="<%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/shops/map') %>">map_search</span>
      <span class="text-[9px]" style="<%= 'color: #e57777;' if current_page?('/shops/map') %>">現在地から探す</span>
    <% end %>

    <%= link_to bookmarks_shops_path, class: "inline-flex flex-col items-center justify-center px-1" do %>
      <span class="material-symbols-outlined text-2xl" style="<%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/shops/bookmarks') %>">favorite</span>
      <span class="text-[9px]" style="<%= 'color: #e57777;' if current_page?('/shops/bookmarks') %>">お気に入り</span>
    <% end %>

    <%= link_to start_diagnoses_path, class: "inline-flex flex-col items-center justify-center px-1" do %>
      <span class="material-symbols-outlined text-2xl" style="<%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/diagnoses/start') %>">edit_note</span>
      <span class="text-[9px]" style="<%= 'color: #e57777;' if current_page?('/diagnoses/start') %>">香りタイプ診断</span>
    <% end %>

    <%= link_to profile_path, class: "inline-flex flex-col items-center justify-center px-1" do %>
      <span class="material-symbols-outlined text-2xl" style="<%= 'font-variation-settings: \'FILL\' 1; color: #e57777;' if current_page?('/profile') %>">person</span>
      <span class="text-[9px]" style="<%= 'color: #e57777;' if current_page?('/profile') %>">マイページ</span>
    <% end %>
  </div>
</div>