config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks",
    sessions: "users/sessions"
  }

  resources :shops do
    resources :reviews, only: %i[new create show edit update destroy], shallow: true
    collection do
      get "search"
      get "map"
      get "list"
      get "bookmarks"
      get "autocomplete"
    end
  end

  resource :profile, only: %i[show edit update]

  resources :shop_bookmarks, only: %i[create destroy]

  resources :diagnoses do
    collection do
      get "start", to: "diagnoses#start"
      get "question/:id", to: "diagnoses#show_question", as: "question"
      post "answer", to: "diagnoses#answer_question"
      get "result", to: "diagnoses#result"
    end
  end

  get "privacy", to: "static_pages#privacy", as: "privacy_policy"

  get "terms", to: "static_pages#terms", as: "terms"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: %i[edit update destroy]
  before_action :set_review, only: %i[edit update destroy]

  def create
    @review = current_user.reviews.build(review_params)
    @review.save
  end

  def edit
    @shop = @review.shop
  end

  def update
    @shop = @review.shop
    @review = Review.find(params[:id])

    if @review.update(update_review_params)
      flash[:notice] = "口コミを更新しました。"
      redirect_to shop_path(@shop)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @review.destroy!
  end

  private

  def set_review
    @review = current_user.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:body).merge(shop_id: params[:shop_id])
  end

  def update_review_params
    params.require(:review).permit(:body)
  end
end

app/views/reviews/_form.html.erb
<div class="p-5" id="review-form">
  <div class="w-full max-w-lg mx-auto">
    <%= form_with model: review, url: shop_reviews_path(shop) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <div class="mb-2">
        <%= f.label :body, class: "block text-gray-700" %>
        <%= f.text_area :body, class: "form-control mt-1 block w-full border rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50 p-2", rows: "4", placeholder: "あなたの体験・感想や購入商品など気軽に投稿してみてください！" %>
      </div>

      <div class="flex justify-center">
        <%= f.submit "口コミを投稿する", class: "cursor-pointer mt-1 bg-main px-10 py-3 text-white rounded hover:bg-opacity-90 transition duration-200 shadow" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/_review.html.erb
<div id="review-<%= review.id %>" class="p-5 border-b border-gray-300">
  <p class="text-base text-gray-600"><%= review.user.name %></p>
  <p class="text-xs text-gray-600"><%= review.created_at.strftime("%Y年%m月%d日") %></p>
  <p class="mt-2 text-gray-800"><%= review.body %></p>

  <% if current_user&.own?(review) %>
    <%= link_to "口コミを編集する", edit_review_path(review), class: "bg-white mt-2 p-1 border inline-block text-xs mr-3 hover:text-main transition duration-400" %>
    <%= link_to "口コミを削除する", review_path(review), class: "bg-white mt-2 p-1 border inline-block text-xs hover:text-main transition duration-400", data: { turbo_method: :delete, turbo_confirm: "口コミを削除すると元に戻せません。\n本当に削除しますか？" } %>
  <% end %>
</div>

app/views/reviews/create.turbo_stream.erb
<% if @review.errors.present? %>
  <%= turbo_stream.replace "review-form" do %>
    <%= render 'reviews/form', review: @review, shop: @review.shop %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-review" do %>
    <%= render 'reviews/review', review: @review %>
  <% end %>
  <%= turbo_stream.replace "review-form" do %>
    <%= render 'reviews/form', review: Review.new, shop: @review.shop %>
  <% end %>
<% end %>

app/views/reviews/destroy.turbo_stream.erb
<%= turbo_stream.remove "review-#{@review.id}" do %>
<% end %>

app/views/reviews/edit.html.erb
<div class="p-5" id="review-form">
  <div class="w-full max-w-lg mx-auto">
     <h2 class="text-xl md:text-2xl font-bold mb-4">口コミの編集（<%= @shop.name %>）</h2>
    <%= form_with model: @review, url: review_path(@review) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <div class="mb-2">
        <%= f.label :body, class: "block text-gray-700" %>
        <%= f.text_area :body, class: "form-control mt-1 block w-full border rounded-md shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50 p-2", rows: "4" %>
      </div>

      <div class="flex justify-center">
        <%= f.submit "口コミを更新する", class: "cursor-pointer mt-1 bg-main px-10 py-3 text-white rounded hover:bg-opacity-90 transition duration-200 shadow" %>
      </div>
    <% end %>
  </div>
</div>